# Generated by Django 3.2.9 on 2022-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='sizemodel',
            name='name',
            field=models.CharField(default=None, max_length=3, verbose_name='name'),
            preserve_default=False,
        ),
    ]
