# Generated by Django 3.2.9 on 2021-12-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTag',
            new_name='ProductTagModel',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.brandmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.categorymodel'),
            preserve_default=False,
        ),
    ]
