# Generated by Django 3.2.9 on 2022-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220116_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'size',
            },
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='SizeModel',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='razmerlar',
            field=models.ManyToManyField(related_name='products', to='product.SizesModel'),
        ),
    ]
