# Generated by Django 3.2.9 on 2022-01-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220114_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colormodel',
            name='code',
            field=models.CharField(max_length=20, verbose_name='code'),
        ),
    ]
