# Generated by Django 3.2.9 on 2022-01-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productmodel_real_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='real_price',
            field=models.IntegerField(default=0, verbose_name='real price'),
        ),
    ]
